#ifndef IO_GITHUB_CODERODDE_HUFFMAN_COMPRESSOR_C_COMPRESSOR_H
#define IO_GITHUB_CODERODDE_HUFFMAN_COMPRESSOR_C_COMPRESSOR_H

void compress(
    char* input_file_name,
    char* output_file_name
);

#endif // IO_GITHUB_CODERODDE_HUFFMAN_COMPRESSOR_C_COMPRESSOR_H