#ifndef IO_GITHUB_CODERODDE_HUFFMAN_COMPRESSOR_C_PRIORITY_QUEUE_H
#define IO_GITHUB_CODERODDE_HUFFMAN_COMPRESSOR_C_PRIORITY_QUEUE_H

typedef struct PriorityQueue {
    
} PriorityQueue;

#endif // IO_GITHUB_CODERODDE_HUFFMAN_COMPRESSOR_C_PRIORITY_QUEUE_H